import type { CatalogItem, ID, ItemGroup } from './types'

/** Стабильные id встроенных позиций — для ссылок из кода. Менять нельзя: на них ссылаются записи пользователя. */
export const CATALOG_ID = {
  engineOil: 'item.engine_oil',
  oilFilter: 'item.oil_filter',
  airFilter: 'item.air_filter',
  cabinFilter: 'item.cabin_filter',
  fuelFilter: 'item.fuel_filter',
  sparkPlugs: 'item.spark_plugs',
  glowPlugs: 'item.glow_plugs',
  ignitionCoil: 'item.ignition_coil',
  timingBelt: 'item.timing_belt',
  timingChain: 'item.timing_chain',
  driveBelt: 'item.drive_belt',
  waterPump: 'item.water_pump',
  coolant: 'item.coolant',
  brakeFluid: 'item.brake_fluid',
  atf: 'item.atf',
  mtf: 'item.mtf',
  transferCaseOil: 'item.transfer_case_oil',
  diffOil: 'item.diff_oil',
  powerSteeringFluid: 'item.power_steering_fluid',
  clutch: 'item.clutch',
  brakePadsFront: 'item.brake_pads_front',
  brakePadsRear: 'item.brake_pads_rear',
  brakeDiscsFront: 'item.brake_discs_front',
  brakeDiscsRear: 'item.brake_discs_rear',
  shockAbsorbers: 'item.shock_absorbers',
  suspensionCheck: 'item.suspension_check',
  wheelAlignment: 'item.wheel_alignment',
  stabilizerLinks: 'item.stabilizer_links',
  cvBoots: 'item.cv_boots',
  battery: 'item.battery',
  bulbs: 'item.bulbs',
  wiperBlades: 'item.wiper_blades',
  acService: 'item.ac_service',
  tiresSummer: 'item.tires_summer',
  tiresWinter: 'item.tires_winter',
  tireFitting: 'item.tire_fitting',
  washerFluid: 'item.washer_fluid',
  other: 'item.other',
  // Двигатель: механика, охлаждение, питание, впуск и выпуск
  valveCoverGasket: 'item.valve_cover_gasket',
  headGasket: 'item.head_gasket',
  oilPanGasket: 'item.oil_pan_gasket',
  crankshaftSeals: 'item.crankshaft_seals',
  valveStemSeals: 'item.valve_stem_seals',
  engineMounts: 'item.engine_mounts',
  engineOverhaul: 'item.engine_overhaul',
  engineDiagnostics: 'item.engine_diagnostics',
  pcvValve: 'item.pcv_valve',
  turbocharger: 'item.turbocharger',
  thermostat: 'item.thermostat',
  radiator: 'item.radiator',
  radiatorFan: 'item.radiator_fan',
  coolantHoses: 'item.coolant_hoses',
  oxygenSensor: 'item.oxygen_sensor',
  crankshaftSensor: 'item.crankshaft_sensor',
  mafSensor: 'item.maf_sensor',
  fuelInjectors: 'item.fuel_injectors',
  fuelPump: 'item.fuel_pump',
  highPressureFuelPump: 'item.high_pressure_fuel_pump',
  throttleBody: 'item.throttle_body',
  egrValve: 'item.egr_valve',
  catalyticConverter: 'item.catalytic_converter',
  particulateFilter: 'item.particulate_filter',
  exhaustDownpipe: 'item.exhaust_downpipe',
  exhaustFlexPipe: 'item.exhaust_flex_pipe',
  muffler: 'item.muffler',
  // Фильтры, зажигание, ремни
  atfFilter: 'item.atf_filter',
  ignitionWires: 'item.ignition_wires',
  driveBeltTensioner: 'item.drive_belt_tensioner',
  camPhaser: 'item.cam_phaser',
  // Трансмиссия
  cvJointOuter: 'item.cv_joint_outer',
  cvJointInner: 'item.cv_joint_inner',
  driveShaft: 'item.drive_shaft',
  releaseBearing: 'item.release_bearing',
  flywheel: 'item.flywheel',
  clutchMasterCylinder: 'item.clutch_master_cylinder',
  clutchSlaveCylinder: 'item.clutch_slave_cylinder',
  gearboxMount: 'item.gearbox_mount',
  gearbox: 'item.gearbox',
  dsgMechatronic: 'item.dsg_mechatronic',
  haldexOil: 'item.haldex_oil',
  propellerShaft: 'item.propeller_shaft',
  // Тормоза
  brakeCaliperFront: 'item.brake_caliper_front',
  brakeCaliperRear: 'item.brake_caliper_rear',
  caliperGuidePins: 'item.caliper_guide_pins',
  brakeDrumsRear: 'item.brake_drums_rear',
  wheelCylindersRear: 'item.wheel_cylinders_rear',
  brakeMasterCylinder: 'item.brake_master_cylinder',
  brakeBooster: 'item.brake_booster',
  brakeHoses: 'item.brake_hoses',
  brakeLines: 'item.brake_lines',
  parkingBrakeCable: 'item.parking_brake_cable',
  absSensor: 'item.abs_sensor',
  // Подвеска
  frontLowerArm: 'item.front_lower_arm',
  frontUpperArm: 'item.front_upper_arm',
  frontArmBushings: 'item.front_arm_bushings',
  ballJoint: 'item.ball_joint',
  frontStruts: 'item.front_struts',
  frontStrutMounts: 'item.front_strut_mounts',
  coilSpringsFront: 'item.coil_springs_front',
  hubBearingFront: 'item.hub_bearing_front',
  rearControlArms: 'item.rear_control_arms',
  rearArmBushings: 'item.rear_arm_bushings',
  rearBeamBushings: 'item.rear_beam_bushings',
  shockAbsorbersRear: 'item.shock_absorbers_rear',
  rearShockMounts: 'item.rear_shock_mounts',
  coilSpringsRear: 'item.coil_springs_rear',
  hubBearingRear: 'item.hub_bearing_rear',
  shockBootsBumpStops: 'item.shock_boots_bump_stops',
  stabilizerBushings: 'item.stabilizer_bushings',
  // Рулевое управление
  tieRod: 'item.tie_rod',
  tieRodEnd: 'item.tie_rod_end',
  steeringRack: 'item.steering_rack',
  steeringRackBoots: 'item.steering_rack_boots',
  powerSteeringPump: 'item.power_steering_pump',
  electricPowerSteering: 'item.electric_power_steering',
  steeringShaft: 'item.steering_shaft',
  // Электрика и свет
  alternator: 'item.alternator',
  starter: 'item.starter',
  headlights: 'item.headlights',
  fogLights: 'item.fog_lights',
  tailLights: 'item.tail_lights',
  lowBeamBulbs: 'item.low_beam_bulbs',
  highBeamBulbs: 'item.high_beam_bulbs',
  headlightPolishing: 'item.headlight_polishing',
  fuses: 'item.fuses',
  wiring: 'item.wiring',
  clockSpring: 'item.clock_spring',
  parkingSensors: 'item.parking_sensors',
  computerDiagnostics: 'item.computer_diagnostics',
  // Климат
  heaterCore: 'item.heater_core',
  heaterBlower: 'item.heater_blower',
  acCompressor: 'item.ac_compressor',
  acCondenser: 'item.ac_condenser',
  // Кузов
  windshield: 'item.windshield',
  sideMirrors: 'item.side_mirrors',
  windowRegulator: 'item.window_regulator',
  wiperLinkage: 'item.wiper_linkage',
  bumperFront: 'item.bumper_front',
  bumperRear: 'item.bumper_rear',
  fenderLiners: 'item.fender_liners',
  skidPlate: 'item.skid_plate',
  bodyRepair: 'item.body_repair',
  bodyPainting: 'item.body_painting',
  bodyPolishing: 'item.body_polishing',
  anticorrosion: 'item.anticorrosion',
  windowTint: 'item.window_tint',
  carWash: 'item.car_wash',
  interiorCleaning: 'item.interior_cleaning',
  // Колёса и шины
  wheelBalancing: 'item.wheel_balancing',
  wheels: 'item.wheels',
  wheelStraightening: 'item.wheel_straightening',
  tireRepair: 'item.tire_repair',
  tireStorage: 'item.tire_storage',
  tiresAllSeason: 'item.tires_all_season',
  tpmsSensors: 'item.tpms_sensors',
} as const satisfies Record<string, ID>

export const ITEM_GROUP_LABELS: Record<ItemGroup, string> = {
  engine: 'Двигатель',
  fluids: 'Жидкости',
  filters: 'Фильтры',
  ignition: 'Зажигание',
  timing: 'ГРМ и ремни',
  transmission: 'Трансмиссия',
  brakes: 'Тормоза',
  suspension: 'Подвеска',
  steering: 'Рулевое управление',
  electrical: 'Электрика',
  climate: 'Климат',
  body: 'Кузов',
  tires: 'Шины',
  other: 'Прочее',
}

function item(id: ID, name: string, group: ItemGroup, km?: number, months?: number): CatalogItem {
  return {
    id,
    name,
    group,
    builtin: true,
    createdAt: 0,
    updatedAt: 0,
    ...(km !== undefined && { defaultIntervalKm: km }),
    ...(months !== undefined && { defaultIntervalMonths: months }),
  }
}

const C = CATALOG_ID

/** Встроенный каталог узлов. `createdAt/updatedAt = 0`: любая правка пользователя побеждает при слиянии. */
export const BUILTIN_CATALOG: CatalogItem[] = [
  item(C.engineOil, 'Моторное масло', 'engine', 10000, 12),
  item(C.oilFilter, 'Масляный фильтр', 'filters', 10000, 12),
  item(C.airFilter, 'Воздушный фильтр', 'filters', 20000, 24),
  item(C.cabinFilter, 'Салонный фильтр', 'filters', 15000, 12),
  item(C.fuelFilter, 'Топливный фильтр', 'filters', 40000, 48),
  item(C.sparkPlugs, 'Свечи зажигания', 'ignition', 30000, 36),
  item(C.glowPlugs, 'Свечи накаливания', 'ignition', 60000),
  item(C.ignitionCoil, 'Катушка зажигания', 'ignition'),
  item(C.timingBelt, 'Ремень ГРМ с роликами', 'timing', 60000, 60),
  item(C.timingChain, 'Цепь ГРМ', 'timing', 150000),
  item(C.driveBelt, 'Приводной ремень', 'timing', 60000, 48),
  item(C.waterPump, 'Помпа', 'engine', 60000),
  item(C.coolant, 'Охлаждающая жидкость', 'fluids', 60000, 48),
  item(C.brakeFluid, 'Тормозная жидкость', 'fluids', undefined, 24),
  item(C.atf, 'Масло АКПП/вариатора', 'transmission', 60000),
  item(C.mtf, 'Масло МКПП', 'transmission', 90000),
  item(C.transferCaseOil, 'Масло раздаточной коробки', 'transmission', 60000),
  item(C.diffOil, 'Масло редуктора', 'transmission', 60000),
  item(C.powerSteeringFluid, 'Жидкость ГУР', 'steering', 60000, 48),
  item(C.clutch, 'Сцепление', 'transmission'),
  item(C.brakePadsFront, 'Колодки тормозные передние', 'brakes', 30000),
  item(C.brakePadsRear, 'Колодки тормозные задние', 'brakes', 50000),
  item(C.brakeDiscsFront, 'Диски тормозные передние', 'brakes', 80000),
  item(C.brakeDiscsRear, 'Диски тормозные задние', 'brakes', 100000),
  item(C.shockAbsorbers, 'Амортизаторы', 'suspension', 80000),
  item(C.suspensionCheck, 'Диагностика подвески', 'suspension', 15000, 12),
  item(C.wheelAlignment, 'Развал-схождение', 'suspension', 20000, 12),
  item(C.stabilizerLinks, 'Стойки стабилизатора', 'suspension'),
  item(C.cvBoots, 'Пыльники ШРУС', 'suspension'),
  item(C.battery, 'Аккумулятор', 'electrical', undefined, 48),
  item(C.bulbs, 'Лампы', 'electrical'),
  item(C.wiperBlades, 'Щётки стеклоочистителя', 'body', undefined, 12),
  item(C.acService, 'Обслуживание кондиционера', 'climate', undefined, 24),
  item(C.tiresSummer, 'Шины летние', 'tires'),
  item(C.tiresWinter, 'Шины зимние', 'tires'),
  item(C.tireFitting, 'Шиномонтаж', 'tires', undefined, 6),
  item(C.washerFluid, 'Омывающая жидкость', 'fluids'),
  item(C.other, 'Прочее', 'other'),
  // Вторая версия каталога: позиции только дописываются в конец. Интервала по умолчанию у них нет —
  // общепринятого пробега замены для этих узлов не существует, владелец задаёт его в напоминании сам.
  item(C.valveCoverGasket, 'Прокладка клапанной крышки', 'engine'),
  item(C.headGasket, 'Прокладка ГБЦ', 'engine'),
  item(C.oilPanGasket, 'Прокладка поддона картера', 'engine'),
  item(C.crankshaftSeals, 'Сальники коленвала', 'engine'),
  item(C.valveStemSeals, 'Маслосъёмные колпачки', 'engine'),
  item(C.engineMounts, 'Опоры двигателя', 'engine'),
  item(C.engineOverhaul, 'Капремонт двигателя', 'engine'),
  item(C.engineDiagnostics, 'Диагностика двигателя', 'engine'),
  item(C.pcvValve, 'Клапан вентиляции картера', 'engine'),
  item(C.turbocharger, 'Турбина', 'engine'),
  item(C.thermostat, 'Термостат', 'engine'),
  item(C.radiator, 'Радиатор охлаждения', 'engine'),
  item(C.radiatorFan, 'Вентилятор радиатора', 'engine'),
  item(C.coolantHoses, 'Патрубки системы охлаждения', 'engine'),
  item(C.oxygenSensor, 'Датчик кислорода (лямбда-зонд)', 'engine'),
  item(C.crankshaftSensor, 'Датчик коленвала', 'engine'),
  item(C.mafSensor, 'Датчик массового расхода воздуха (ДМРВ)', 'engine'),
  item(C.fuelInjectors, 'Форсунки', 'engine'),
  item(C.fuelPump, 'Топливный насос (бензонасос)', 'engine'),
  item(C.highPressureFuelPump, 'Топливный насос высокого давления (ТНВД)', 'engine'),
  item(C.throttleBody, 'Дроссельная заслонка', 'engine'),
  item(C.egrValve, 'Клапан EGR (ЕГР)', 'engine'),
  item(C.catalyticConverter, 'Катализатор', 'engine'),
  item(C.particulateFilter, 'Сажевый фильтр (DPF)', 'engine'),
  item(C.exhaustDownpipe, 'Приёмная труба глушителя', 'engine'),
  item(C.exhaustFlexPipe, 'Гофра глушителя', 'engine'),
  item(C.muffler, 'Глушитель', 'engine'),
  item(C.atfFilter, 'Фильтр АКПП', 'filters'),
  item(C.ignitionWires, 'Высоковольтные провода', 'ignition'),
  item(C.driveBeltTensioner, 'Натяжитель и ролики приводного ремня', 'timing'),
  item(C.camPhaser, 'Фазорегулятор', 'timing'),
  item(C.cvJointOuter, 'ШРУС наружный', 'transmission'),
  item(C.cvJointInner, 'ШРУС внутренний', 'transmission'),
  item(C.driveShaft, 'Привод (полуось)', 'transmission'),
  item(C.releaseBearing, 'Выжимной подшипник', 'transmission'),
  item(C.flywheel, 'Маховик', 'transmission'),
  item(C.clutchMasterCylinder, 'Цилиндр сцепления главный', 'transmission'),
  item(C.clutchSlaveCylinder, 'Цилиндр сцепления рабочий', 'transmission'),
  item(C.gearboxMount, 'Опора КПП', 'transmission'),
  item(C.gearbox, 'Коробка передач', 'transmission'),
  item(C.dsgMechatronic, 'Мехатроник DSG', 'transmission'),
  item(C.haldexOil, 'Масло муфты Haldex', 'transmission'),
  item(C.propellerShaft, 'Карданный вал', 'transmission'),
  item(C.brakeCaliperFront, 'Суппорт тормозной передний', 'brakes'),
  item(C.brakeCaliperRear, 'Суппорт тормозной задний', 'brakes'),
  item(C.caliperGuidePins, 'Направляющие суппорта', 'brakes'),
  item(C.brakeDrumsRear, 'Барабаны тормозные задние', 'brakes'),
  item(C.wheelCylindersRear, 'Цилиндры тормозные задние', 'brakes'),
  item(C.brakeMasterCylinder, 'Цилиндр тормозной главный', 'brakes'),
  item(C.brakeBooster, 'Вакуумный усилитель тормозов', 'brakes'),
  item(C.brakeHoses, 'Тормозные шланги', 'brakes'),
  item(C.brakeLines, 'Тормозные трубки', 'brakes'),
  item(C.parkingBrakeCable, 'Трос стояночного тормоза', 'brakes'),
  item(C.absSensor, 'Датчик ABS (АБС)', 'brakes'),
  item(C.frontLowerArm, 'Рычаг передний нижний', 'suspension'),
  item(C.frontUpperArm, 'Рычаг передний верхний', 'suspension'),
  item(C.frontArmBushings, 'Сайлентблоки передних рычагов', 'suspension'),
  item(C.ballJoint, 'Шаровая опора', 'suspension'),
  item(C.frontStruts, 'Стойки амортизаторов передние', 'suspension'),
  item(C.frontStrutMounts, 'Опоры передних стоек', 'suspension'),
  item(C.coilSpringsFront, 'Пружины подвески передние', 'suspension'),
  item(C.hubBearingFront, 'Подшипник ступицы передний', 'suspension'),
  item(C.rearControlArms, 'Рычаги задней подвески', 'suspension'),
  item(C.rearArmBushings, 'Сайлентблоки задних рычагов', 'suspension'),
  item(C.rearBeamBushings, 'Сайлентблоки задней балки', 'suspension'),
  item(C.shockAbsorbersRear, 'Амортизаторы задние', 'suspension'),
  item(C.rearShockMounts, 'Опоры задних амортизаторов', 'suspension'),
  item(C.coilSpringsRear, 'Пружины подвески задние', 'suspension'),
  item(C.hubBearingRear, 'Подшипник ступицы задний', 'suspension'),
  item(C.shockBootsBumpStops, 'Пыльники и отбойники амортизаторов', 'suspension'),
  item(C.stabilizerBushings, 'Втулки стабилизатора', 'suspension'),
  item(C.tieRod, 'Рулевая тяга', 'steering'),
  item(C.tieRodEnd, 'Рулевой наконечник', 'steering'),
  item(C.steeringRack, 'Рулевая рейка', 'steering'),
  item(C.steeringRackBoots, 'Пыльники рулевой рейки', 'steering'),
  item(C.powerSteeringPump, 'Насос ГУР', 'steering'),
  item(C.electricPowerSteering, 'Электроусилитель руля (ЭУР)', 'steering'),
  item(C.steeringShaft, 'Рулевой вал (карданчик)', 'steering'),
  item(C.alternator, 'Генератор', 'electrical'),
  item(C.starter, 'Стартер', 'electrical'),
  item(C.headlights, 'Фары', 'electrical'),
  item(C.fogLights, 'Противотуманные фары', 'electrical'),
  item(C.tailLights, 'Фонари задние', 'electrical'),
  item(C.lowBeamBulbs, 'Лампы ближнего света', 'electrical'),
  item(C.highBeamBulbs, 'Лампы дальнего света', 'electrical'),
  item(C.headlightPolishing, 'Полировка фар', 'electrical'),
  item(C.fuses, 'Предохранители и реле', 'electrical'),
  item(C.wiring, 'Электропроводка', 'electrical'),
  item(C.clockSpring, 'Подрулевой шлейф', 'electrical'),
  item(C.parkingSensors, 'Парктроник', 'electrical'),
  item(C.computerDiagnostics, 'Компьютерная диагностика', 'electrical'),
  item(C.heaterCore, 'Радиатор печки', 'climate'),
  item(C.heaterBlower, 'Вентилятор печки', 'climate'),
  item(C.acCompressor, 'Компрессор кондиционера', 'climate'),
  item(C.acCondenser, 'Радиатор кондиционера', 'climate'),
  item(C.windshield, 'Лобовое стекло', 'body'),
  item(C.sideMirrors, 'Зеркала боковые', 'body'),
  item(C.windowRegulator, 'Стеклоподъёмник', 'body'),
  item(C.wiperLinkage, 'Трапеция стеклоочистителя', 'body'),
  item(C.bumperFront, 'Бампер передний', 'body'),
  item(C.bumperRear, 'Бампер задний', 'body'),
  item(C.fenderLiners, 'Подкрылки', 'body'),
  item(C.skidPlate, 'Защита картера', 'body'),
  item(C.bodyRepair, 'Кузовной ремонт', 'body'),
  item(C.bodyPainting, 'Покраска кузова', 'body'),
  item(C.bodyPolishing, 'Полировка кузова', 'body'),
  item(C.anticorrosion, 'Обработка кузова антикором', 'body'),
  item(C.windowTint, 'Тонировка', 'body'),
  item(C.carWash, 'Мойка', 'body'),
  item(C.interiorCleaning, 'Химчистка салона', 'body'),
  item(C.wheelBalancing, 'Балансировка колёс', 'tires'),
  item(C.wheels, 'Диски колёсные', 'tires'),
  item(C.wheelStraightening, 'Правка колёсных дисков', 'tires'),
  item(C.tireRepair, 'Ремонт шины (прокол)', 'tires'),
  item(C.tireStorage, 'Хранение шин', 'tires'),
  item(C.tiresAllSeason, 'Шины всесезонные', 'tires'),
  item(C.tpmsSensors, 'Датчики давления в шинах', 'tires'),
]

/** Позиции, для которых мастер новой машины предлагает включить напоминания. */
export const STARTER_REMINDER_ITEM_IDS: ID[] = [
  C.engineOil,
  C.oilFilter,
  C.airFilter,
  C.cabinFilter,
  C.sparkPlugs,
  C.brakeFluid,
  C.coolant,
  C.timingBelt,
]
