import type { TireSeason } from './types'

/**
 * Подсказки для шин: популярные в России размеры, бренды и модели. Только подсказки — владелец может вписать любое.
 * Данные — `TIRE_SIZES` и `TIRE_BRANDS` ниже.
 */

export interface TireModel {
  name: string
  season: TireSeason
  /** Зимняя шипованная; для нешипованной («липучки») — false. */
  studded?: boolean
  /** Прежние названия той же шины: Ikon Character Ice 8 — бывший Nokian Nordman 8. */
  aka?: string[]
}

export interface TireBrand {
  brand: string
  /** Прежние и народные названия: «Nokian» → Ikon Tyres. */
  aka?: string[]
  models: TireModel[]
}

const SIZE_RE = /^\s*(\d{3})\s*[/\s]\s*(\d{2})\s*(?:Z?R)?\s*(\d{2}(?:[.,]5)?)\s*(C)?\s*$/i

/** «205/55r16», «205 55 16», «225/45 ZR17» → «205/55 R16»; не похоже на размер — как ввели (без пробелов по краям). */
export function formatTireSize(input: string): string {
  const m = SIZE_RE.exec(input)
  if (!m) return input.trim()
  const [, width, profile, rim, cargo] = m
  return `${width}/${profile} R${rim!.replace(',', '.')}${cargo ? 'C' : ''}`
}

const digits = (s: string) => s.replace(/\D/g, '')

/** Поиск размера по цифрам: «2055516», «205 55», «r16». */
export function matchesTireSize(size: string, query: string): boolean {
  return digits(size).includes(digits(query))
}

const norm = (s: string) => s.trim().toLowerCase().replaceAll('ё', 'е')

/** Бренд по названию или прежнему имени, без учёта регистра. */
export function findTireBrand(name: string): TireBrand | undefined {
  const q = norm(name)
  if (!q) return undefined
  return TIRE_BRANDS.find((b) => norm(b.brand) === q || b.aka?.some((a) => norm(a) === q))
}

/** Модели бренда; сначала нужного сезона. */
export function tireModels(brand: string, season?: TireSeason): TireModel[] {
  const models = findTireBrand(brand)?.models ?? []
  if (!season) return models
  return [...models.filter((m) => m.season === season), ...models.filter((m) => m.season !== season)]
}

const W = (name: string, studded: boolean, aka?: string[]): TireModel => ({
  name,
  season: 'winter',
  studded,
  ...(aka && { aka }),
})
const S = (name: string, aka?: string[]): TireModel => ({ name, season: 'summer', ...(aka && { aka }) })
const A = (name: string, aka?: string[]): TireModel => ({ name, season: 'allSeason', ...(aka && { aka }) })

/** Популярные в России размеры легковых машин и кроссоверов (C — лёгкий грузовик): по диаметру, ширине, профилю. */
export const TIRE_SIZES: string[] = [
  '155/70 R13',
  '165/70 R13',
  '175/70 R13',
  '165/60 R14',
  '165/65 R14',
  '165/70 R14',
  '175/65 R14',
  '175/70 R14',
  '185/60 R14',
  '185/65 R14',
  '185/70 R14',
  '175/65 R15',
  '185/55 R15',
  '185/60 R15',
  '185/65 R15',
  '195/50 R15',
  '195/55 R15',
  '195/60 R15',
  '195/65 R15',
  '205/60 R15',
  '205/65 R15',
  '205/70 R15',
  '205/75 R15',
  '215/65 R15',
  '215/70 R15',
  '225/70 R15',
  '235/75 R15',
  '175/80 R16',
  '185/75 R16',
  '195/50 R16',
  '195/55 R16',
  '195/60 R16',
  '205/50 R16',
  '205/55 R16',
  '205/60 R16',
  '205/65 R16',
  '215/55 R16',
  '215/60 R16',
  '215/65 R16',
  '215/70 R16',
  '225/55 R16',
  '225/60 R16',
  '225/70 R16',
  '225/75 R16',
  '235/60 R16',
  '235/70 R16',
  '245/70 R16',
  '265/70 R16',
  '185/75 R16C',
  '195/75 R16C',
  '205/75 R16C',
  '215/65 R16C',
  '205/45 R17',
  '205/50 R17',
  '205/55 R17',
  '215/45 R17',
  '215/50 R17',
  '215/55 R17',
  '215/60 R17',
  '215/65 R17',
  '225/45 R17',
  '225/50 R17',
  '225/55 R17',
  '225/60 R17',
  '225/65 R17',
  '235/45 R17',
  '235/55 R17',
  '235/60 R17',
  '235/65 R17',
  '245/45 R17',
  '245/65 R17',
  '265/65 R17',
  '215/55 R18',
  '225/40 R18',
  '225/45 R18',
  '225/55 R18',
  '225/60 R18',
  '235/40 R18',
  '235/45 R18',
  '235/50 R18',
  '235/55 R18',
  '235/60 R18',
  '245/40 R18',
  '245/45 R18',
  '255/55 R18',
  '255/60 R18',
  '265/60 R18',
  '285/60 R18',
  '225/45 R19',
  '225/55 R19',
  '235/35 R19',
  '235/50 R19',
  '235/55 R19',
  '245/40 R19',
  '245/45 R19',
  '245/55 R19',
  '255/40 R19',
  '255/50 R19',
  '255/55 R19',
  '275/40 R19',
  '245/45 R20',
  '255/40 R20',
  '255/45 R20',
  '255/50 R20',
  '265/50 R20',
  '275/40 R20',
  '275/45 R20',
  '285/45 R20',
  '285/50 R20',
  '315/35 R20',
  '265/40 R21',
  '265/45 R21',
  '275/40 R21',
  '285/40 R21',
  '295/35 R21',
]

/**
 * Бренды и модели, которые продаются в России (исследование рынка 2026-09: citytire, kolesa.ru, shinservice, autoshini,
 * сайты производителей). У переименованных моделей Ikon — прежние имена Nokian в `aka`.
 */
export const TIRE_BRANDS: TireBrand[] = [
  {
    brand: 'Ikon Tyres',
    aka: ['Nokian', 'Nokian Tyres', 'Nordman', 'Айкон'],
    models: [
      W('Autograph Ice 10', true),
      W('Autograph Snow 5', false),
      W('Autograph Ice 9', true, ['Hakkapeliitta 9']),
      W('Autograph Ice 9 SUV', true, ['Hakkapeliitta 9 SUV']),
      W('Autograph Snow 3', false, ['Hakkapeliitta R3']),
      W('Autograph Snow 3 SUV', false, ['Hakkapeliitta R3 SUV']),
      W('Character Ice 8', true, ['Nordman 8']),
      W('Character Ice 8 SUV', true, ['Nordman 8 SUV']),
      W('Character Ice 7 SUV', true, ['Nordman 7 SUV']),
      W('Character Snow 2', false, ['Nordman RS2']),
      W('Character Snow 2 SUV', false, ['Nordman RS2 SUV']),
      W('Nordman 7', true),
      W('Nordman 5', true),
      W('Hakkapeliitta 10', true),
      W('Hakkapeliitta 8', true),
      W('Hakkapeliitta R2', false),
      S('Autograph Ultra 2', ['Hakka Black 2']),
      S('Autograph Ultra 2 SUV', ['Hakka Black 2 SUV']),
      S('Autograph Aqua 3', ['Hakka Blue 3']),
      S('Autograph Aqua 3 SUV', ['Hakka Blue 3 SUV']),
      S('Autograph Eco 3', ['Hakka Green 3']),
      S('Character Ultra', ['Nordman SZ2']),
      S('Character Eco', ['Nordman SX3']),
      S('Character Aqua SUV', ['Nordman S2 SUV']),
      S('Hakka Blue 2'),
      S('Hakka Green 2'),
      S('Nordman SX2'),
    ],
  },
  {
    brand: 'Cordiant',
    aka: ['Кордиант'],
    models: [
      W('Snow Cross 2', true),
      W('Snow Cross 2 SUV', true),
      W('Snow Cross', true),
      W('Sno-Max', true),
      W('Polar 2', true),
      W('Winter Drive 2', false),
      W('Winter Drive', false),
      W('Polar SL', false),
      S('Comfort 2'),
      S('Sport 3'),
      S('Road Runner'),
      S('Run Tour'),
      S('Gravity'),
      S('All Terrain'),
      S('Off Road 2'),
    ],
  },
  {
    brand: 'Кама',
    aka: ['KAMA', 'Kama', 'Нижнекамскшина'],
    models: [
      W('Alga', true),
      W('Alga SUV', true),
      W('Euro-519', true),
      W('505 Irbis', true),
      W('Euro-518', true),
      W('515', true),
      S('Breeze'),
      S('Euro-129'),
      S('Euro-236'),
      S('Grant'),
      S('217'),
      A('365'),
      A('365 SUV'),
      A('Flame'),
    ],
  },
  {
    brand: 'Viatti',
    aka: ['Виатти'],
    models: [
      W('Nordico 2', true),
      W('Brina Nordico V-522', true),
      W('Bosco Nordico V-523', true),
      W('Brina V-521', false),
      W('Bosco S/T V-526', false),
      S('Strada Asimmetrico V-130'),
      S('Strada 2 V-134'),
      S('Bosco A/T V-237'),
      S('Bosco H/T V-238'),
    ],
  },
  {
    brand: 'Tunga',
    aka: ['Тунга'],
    models: [W('Nordway 3', true), W('Nordway 2', true), W('Nordway', true), S('Zodiak 2'), S('Camina')],
  },
  {
    brand: 'Amtel',
    aka: ['Амтел'],
    models: [
      W('NordMaster Evo', true),
      W('NordMaster ST-310', true),
      S('Planet EVO'),
      S('Planet FT-501'),
      S('Planet 2P'),
      A('Cruise 4x4'),
    ],
  },
  {
    brand: 'Белшина',
    aka: ['Belshina'],
    models: [
      W('Artmotion Spike', true),
      W('Artmotion Snow', false),
      W('Artmotion Snow HP', false),
      S('Artmotion'),
      S('Artmotion HP'),
      S('Astarta SUV'),
      A('Artmotion All Seasons'),
    ],
  },
  {
    brand: 'Attar',
    aka: ['Аттар'],
    models: [W('W01', true), W('W02', true)],
  },
  {
    brand: 'Formula',
    aka: ['Pirelli Formula', 'Формула'],
    models: [W('Ice', true), W('Ice FR', false), S('Energy')],
  },
  {
    brand: 'Pirelli',
    aka: ['Пирелли'],
    models: [
      W('Ice Zero 2', true),
      W('Scorpion Ice Zero 2', true),
      W('Winter Ice Zero', true),
      W('Ice Zero FR 3', false),
      W('Ice Zero FR', false),
      W('Winter Sottozero 3', false),
      S('Cinturato P7'),
      S('Cinturato P1 Verde'),
      S('Powergy'),
      S('P Zero'),
      S('Scorpion Verde'),
      A('Scorpion Verde All Season'),
    ],
  },
  {
    brand: 'Michelin',
    aka: ['Мишлен'],
    models: [
      W('X-Ice North 4', true),
      W('X-Ice North 4 SUV', true),
      W('X-Ice North 3', true),
      W('Latitude X-Ice North 2+', true),
      W('X-Ice Snow', false),
      W('X-Ice Snow SUV', false),
      W('X-Ice XI3', false),
      W('Alpin 6', false),
      S('Primacy 4'),
      S('Primacy 4+'),
      S('Pilot Sport 4'),
      S('Pilot Sport 4 SUV'),
      S('Pilot Sport 5'),
      S('Energy XM2+'),
      S('Latitude Sport 3'),
      A('CrossClimate 2'),
    ],
  },
  {
    brand: 'Continental',
    aka: ['Континенталь'],
    models: [
      W('IceContact 3', true),
      W('IceContact 2', true),
      W('VikingContact 7', false),
      W('VikingContact 6', false),
      W('WinterContact TS 870', false),
      S('PremiumContact 6'),
      S('PremiumContact 7'),
      S('EcoContact 6'),
      S('UltraContact'),
      S('ContiSportContact 5'),
      S('SportContact 7'),
      S('CrossContact LX2'),
      A('AllSeasonContact 2'),
    ],
  },
  {
    brand: 'Gislaved',
    aka: ['Гиславед'],
    models: [
      W('One W', true),
      W('SpikeControl', true),
      W('IceControl', true),
      W('Nord Frost 200', true),
      W('Nord Frost 100', true),
      W('ArcticControl', false),
      W('Soft Frost 200', false),
      S('PremiumControl'),
      S('UltraControl'),
      S('EcoControl'),
      S('ActiveControl'),
      S('TerraControl'),
      S('Ultra Speed 2'),
    ],
  },
  {
    brand: 'Matador',
    aka: ['Матадор'],
    models: [
      W('MP 30 Sibir Ice 2', true),
      W('MP 30 Sibir Ice 2 SUV', true),
      W('MP 50 Sibir Ice', true),
      W('MP 54 Sibir Snow', false),
      W('MP 93 Nordicca', false),
      S('MP 47 Hectorra 3'),
      S('Hectorra 5'),
      S('MP 44 Elite 3'),
      S('MP 16 Stella 2'),
      S('MP 82 Conquerra 2'),
    ],
  },
  {
    brand: 'Torero',
    aka: ['Тореро'],
    models: [W('MP30', true), S('MP47'), S('MP72'), S('MP82')],
  },
  {
    brand: 'Bridgestone',
    aka: ['Бриджстоун'],
    models: [
      W('Blizzak Spike-03', true),
      W('Blizzak Spike-02', true),
      W('Ice Cruiser 7000', true),
      W('Blizzak Revo GZ', false),
      W('Blizzak VRX2', false),
      W('Blizzak DM-V2', false),
      W('Blizzak Ice', false),
      S('Turanza T005'),
      S('Turanza T001'),
      S('Ecopia EP150'),
      S('Potenza S001'),
      S('Alenza 001'),
      S('Dueler H/P Sport'),
    ],
  },
  {
    brand: 'Yokohama',
    aka: ['Йокогама'],
    models: [
      W('iceGUARD Stud iG65', true),
      W('iceGUARD Stud iG55', true),
      W('iceGUARD Stud iG35', true),
      W('iceGUARD iG70', false),
      W('iceGUARD iG60', false),
      W('iceGUARD iG50 Plus', false),
      W('iceGUARD SUV G075', false),
      S('BluEarth-ES ES32'),
      S('BluEarth-GT AE51'),
      S('BluEarth-XT AE61'),
      S('Advan Sport V105'),
      S('Geolandar CV G058'),
      S('Geolandar H/T G056'),
      A('Geolandar A/T G015'),
    ],
  },
  {
    brand: 'Toyo',
    aka: ['Тойо'],
    models: [
      W('Observe G3-Ice', true),
      W('Observe Ice-Freezer', true),
      W('Observe GSi-6', false),
      W('Observe GSi-5', false),
      W('Observe Garit GIZ', false),
      S('Proxes CF2'),
      S('Proxes CF3'),
      S('Proxes Comfort'),
      S('Proxes Sport'),
      S('Proxes ST III'),
      S('Nanoenergy 3'),
      S('Open Country U/T'),
      A('Open Country A/T Plus'),
    ],
  },
  {
    brand: 'Nitto',
    aka: ['Нитто'],
    models: [
      W('Therma Spike', true),
      W('NT90W', false),
      S('NT421Q'),
      S('NT860'),
      S('NT830 plus'),
      S('NT555 G2'),
      S('Dura Grappler'),
      A('Terra Grappler G2'),
    ],
  },
  {
    brand: 'Goodyear',
    aka: ['Гудиер'],
    models: [
      W('UltraGrip Arctic 2', true),
      W('UltraGrip Ice Arctic', true),
      W('UltraGrip Ice Arctic SUV', true),
      W('UltraGrip 600', true),
      W('UltraGrip Ice 2', false),
      W('UltraGrip Performance+', false),
      S('EfficientGrip Performance 2'),
      S('EfficientGrip Performance'),
      S('EfficientGrip SUV'),
      S('Eagle F1 Asymmetric 6'),
      S('Eagle F1 Asymmetric 5'),
      A('Vector 4Seasons Gen-3'),
    ],
  },
  {
    brand: 'Dunlop',
    aka: ['Данлоп'],
    models: [
      W('SP Winter Ice 03', true),
      W('SP Winter Ice 02', true),
      W('Grandtrek Ice 03', true),
      W('Grandtrek Ice 02', true),
      W('Winter Maxx WM02', false),
      W('Winter Maxx WM01', false),
      W('Winter Maxx SJ8', false),
      S('SP Sport Maxx 050'),
      S('SP Sport LM705'),
      S('Grandtrek PT3'),
      S('Direzza DZ102'),
      S('Enasave EC300+'),
      A('Grandtrek AT5'),
    ],
  },
  {
    brand: 'Sava',
    aka: ['Сава'],
    models: [
      W('Eskimo Stud', true),
      W('Eskimo Ice', false),
      W('Eskimo HP 2', false),
      S('Intensa HP 2'),
      S('Intensa UHP 2'),
      S('Intensa SUV 2'),
      S('Perfecta'),
    ],
  },
  {
    brand: 'Kormoran',
    aka: ['Корморан'],
    models: [
      W('Stud 2', true),
      W('Snow', false),
      S('Road Performance'),
      S('Ultra High Performance'),
      S('SUV Summer'),
    ],
  },
  {
    brand: 'Hankook',
    aka: ['Ханкук'],
    models: [
      W('Winter i*Pike RS2 W429', true),
      W('Winter i*Pike X W429A', true),
      W('Winter i*Pike RS W419', true),
      W('Winter i*cept iZ3 W636', false),
      W('Winter i*cept iZ2 W616', false),
      W('Winter i*cept X RW10', false),
      S('Ventus Prime 4 K135'),
      S('Ventus Prime 3 K125'),
      S('Kinergy Eco 2 K435'),
      S('Ventus S1 evo3 K127'),
      S('Dynapro HP2 RA33'),
      A('Kinergy 4S2 H750'),
    ],
  },
  {
    brand: 'Laufenn',
    aka: ['Лауфенн'],
    models: [
      W('I Fit Ice LW71', true),
      W('I Fit LW31', false),
      W('I Fit IZ LW51', false),
      S('S Fit EQ+ LK01'),
      S('G Fit EQ+ LK41'),
      S('X Fit HP LA41'),
      A('G Fit 4S LH71'),
    ],
  },
  {
    brand: 'Kumho',
    aka: ['Кумхо'],
    models: [
      W('WinterCraft Ice WI32', true),
      W('WinterCraft Ice WI31', true),
      W('WinterCraft SUV Ice WS31', true),
      W('WinterCraft WI61', false),
      W('WinterCraft WI51', false),
      W('WinterCraft SUV WS71', false),
      W("I'Zen KW31", false),
      S('Ecsta HS52'),
      S('Ecsta HS51'),
      S('Ecsta PS71'),
      S('Ecowing ES31'),
      S('Crugen HP71'),
      A('Solus 4S HA32'),
    ],
  },
  {
    brand: 'Marshal',
    aka: ['Маршал'],
    models: [
      W('WinterCraft Ice WI31', true),
      W("I'Zen KW31", false),
      S('Matrac MH12'),
      S('Matrac MH15'),
      S('Matrac FX MU12'),
    ],
  },
  {
    brand: 'Nexen',
    aka: ['Нексен'],
    models: [
      W('Winguard WinSpike 3', true),
      W('Winguard WinSpike WH62', true),
      W('Winguard WinSpike SUV WS62', true),
      W('Winguard Ice 2', false),
      W('Winguard Ice Plus WH43', false),
      W('Winguard Ice SUV WS5', false),
      S("N'Fera SU1"),
      S("N'Fera Primus"),
      S("N'Fera RU1"),
      S("N'blue HD Plus"),
      S('Roadian HP'),
      A("N'blue 4Season"),
    ],
  },
  {
    brand: 'Roadstone',
    aka: ['Роудстоун'],
    models: [
      W('Winguard WinSpike', true),
      W('Winguard Ice Plus WH43', false),
      S('Eurovis Sport 04'),
      S("N'Fera SU1"),
      S('Roadian HP'),
      A("N'Priz 4S"),
    ],
  },
  {
    brand: 'Maxxis',
    aka: ['Максис'],
    models: [
      W('Premitra Ice Nord NS5', true),
      W('Premitra Ice Nord NP5', true),
      W('ArcticTrekker NP3', true),
      W('Premitra Ice 5 SP5', false),
      W('Premitra Ice 5 SUV SP5', false),
      W('Premitra Ice SP3', false),
      W('Premitra Snow WP6', false),
      S('Premitra HP5'),
      S('Victra Sport 5'),
      S('MA-Z4S Victra'),
      S('Bravo HP-M3'),
      A('Bravo AT-771'),
    ],
  },
  {
    brand: 'Sailun',
    aka: ['Сайлун'],
    models: [
      W('Ice Blazer WST3', true),
      W('Ice Blazer WST1', true),
      W('Ice Blazer Arctic Evo', false),
      W('Ice Blazer Arctic', false),
      W('Ice Blazer Arctic SUV', false),
      W('Ice Blazer Alpine+', false),
      S('Atrezzo Elite'),
      S('Atrezzo ZSR 2'),
      S('Atrezzo ZSR'),
      S('Atrezzo Eco'),
      S('Terramax CVR'),
      S('ERange EV'),
      A('Atrezzo 4Seasons'),
    ],
  },
  {
    brand: 'Triangle',
    aka: ['Триангл'],
    models: [
      W('PS01', true),
      W('IcelynX TI501', true),
      W('SnowLink PL02', false),
      W('PL01', false),
      W('WinterX TW401', false),
      W('EffeXIce TF402', false),
      S('AdvanteX SUV TR259'),
      S('TR257'),
      S('TE301'),
      S('ReliaX TE307'),
      S('EffeXSport TH202'),
      S('AdvanteX TC101'),
      A('SeasonX TA01'),
    ],
  },
  {
    brand: 'Linglong',
    aka: ['LingLong', 'Ling Long', 'Линглонг'],
    models: [
      W('Green-Max Winter Grip 2', true),
      W('Green-Max Winter Grip', true),
      W('Green-Max Winter Grip SUV', true),
      W('Green-Max Winter Ice I-15', false),
      W('Green-Max Winter Ice I-15 SUV', false),
      W('Nord Master', false),
      W('Green-Max Winter UHP', false),
      S('Green-Max HP010'),
      S('Comfort Master'),
      S('Sport Master'),
      S('Crosswind 4x4 HP'),
    ],
  },
  {
    brand: 'Headway',
    aka: ['Хедвей'],
    models: [W('HW503', true), W('HW505', false), W('HW508', false), S('HU901'), S('HR805'), S('HH301')],
  },
  {
    brand: 'Arivo',
    aka: ['Ариво'],
    models: [
      W('Ice Claw ARW8', true),
      W('Ice Claw ARW7', true),
      W('Ice Claw ARW4', true),
      W('Winmaster ProX ARW3', false),
      W('Winmaster ProX ARW5', false),
      W('Winmaster ARW2', false),
      S('Premio ARZero'),
      S('Ultra ARZ5'),
      S('Ultra ARZ4'),
      S('Traverso ARV H/T'),
      A('Carlorful A/S'),
    ],
  },
  {
    brand: 'Tracmax',
    aka: ['Тракмакс'],
    models: [
      W('X-Privilo S500', true),
      W('X-Privilo S360', false),
      W('Ice-Plus S210', false),
      S('X-Privilo TX3'),
      S('X-Privilo TX1'),
      S('X-Privilo H/T'),
    ],
  },
]
