/**
 * Справочные данные VIN: регион (ISO 3779), страна (ISO 3780) и производитель по WMI.
 * Источник — список WMI в статье Wikipedia «Vehicle identification number» (раздел «List of common WMI»,
 * со ссылками на ISO 3780 и SAE J1044). В таблицу попали только коды, которые там есть.
 *
 * `make` — марка для формы машины. Если WMI делят несколько марок (сборка Hyundai и Kia на одном заводе и т. п.),
 * `make` не задан: подставить неверную марку хуже, чем не подставить никакой.
 */
export interface WmiEntry {
  manufacturer: string
  make?: string
  country: string
}

const RU = 'Россия'
const BY = 'Беларусь'
const UA = 'Украина'
const UZ = 'Узбекистан'
const KZ = 'Казахстан'
const CN = 'Китай'
const KR = 'Южная Корея'
const JP = 'Япония'
const DE = 'Германия'
const FR = 'Франция'
const ES = 'Испания'
const IT = 'Италия'
const GB = 'Великобритания'
const CZ = 'Чехия'
const SK = 'Словакия'
const HU = 'Венгрия'
const RO = 'Румыния'
const SE = 'Швеция'
const FI = 'Финляндия'
const NL = 'Нидерланды'
const BE = 'Бельгия'
const PT = 'Португалия'
const BG = 'Болгария'
const RS = 'Сербия'
const TR = 'Турция'
const US = 'США'
const CA = 'Канада'
const MX = 'Мексика'
const BR = 'Бразилия'
const AR = 'Аргентина'
const IN = 'Индия'
const TH = 'Таиланд'
const ID = 'Индонезия'
const MY = 'Малайзия'
const IR = 'Иран'
const ZA = 'ЮАР'
const TW = 'Тайвань'
const VN = 'Вьетнам'
const AU = 'Австралия'

const w = (manufacturer: string, country: string, make?: string): WmiEntry =>
  make === undefined ? { manufacturer, country } : { manufacturer, make, country }

export const WMI_TABLE: Record<string, WmiEntry> = {
  // Россия
  XTA: w('АвтоВАЗ', RU, 'Lada'),
  XTB: w('АЗЛК', RU, 'Moskvich'),
  XTC: w('КАМАЗ', RU, 'KAMAZ'),
  XTF: w('ГолАЗ', RU, 'GolAZ'),
  XTH: w('ГАЗ', RU, 'GAZ'),
  XTT: w('УАЗ', RU, 'UAZ'),
  XTY: w('ЛиАЗ', RU, 'LiAZ'),
  XU1: w('УАЗ (спецавтомобили)', RU, 'UAZ'),
  XUF: w('General Motors Russia', RU),
  XUU: w('Автотор (Chevrolet)', RU, 'Chevrolet'),
  XW7: w('Toyota Motor Manufacturing Russia', RU, 'Toyota'),
  XW8: w('Volkswagen Group Rus', RU),
  XWE: w('Автотор (Hyundai, Kia)', RU),
  X1E: w('КАвЗ', RU, 'KAvZ'),
  X1M: w('ПАЗ', RU, 'PAZ'),
  X4X: w('Автотор (BMW)', RU, 'BMW'),
  X7L: w('Renault Россия', RU, 'Renault'),
  X8J: w('ИМЗ-Урал', RU, 'Ural'),
  X96: w('ГАЗ', RU, 'GAZ'),
  X9F: w('Ford Motor Company ЗАО', RU, 'Ford'),
  X9L: w('GM-АвтоВАЗ', RU),
  X9P: w('Volvo Vostok (грузовики Volvo)', RU, 'Volvo'),
  X9X: w('IMS Avtotrade-12 (Great Wall)', RU, 'Great Wall'),
  Z6F: w('Ford Sollers', RU, 'Ford'),
  Z8N: w('Nissan Manufacturing Rus', RU, 'Nissan'),
  Z8T: w('PCMA Rus (Peugeot, Citroen, Mitsubishi)', RU),
  Z94: w('Hyundai Motor Manufacturing Rus', RU),
  Z9M: w('Mercedes-Benz Trucks Vostok', RU, 'Mercedes-Benz'),

  // СНГ и соседи
  XWB: w('UzDaewoo / GM Uzbekistan / Ravon', UZ),
  Y4K: w('БелДжи', BY, 'Geely'),
  Y6D: w('ЗАЗ', UA, 'ZAZ'),
  Y6J: w('Богдан', UA, 'Bogdan'),
  Y7B: w('Богдан', UA, 'Bogdan'),
  Y6U: w('Еврокар (Skoda)', UA, 'Skoda'),
  Y7C: w('КрАСЗ (Great Wall)', UA, 'Great Wall'),
  MX3: w('Hyundai Trans Auto', KZ, 'Hyundai'),
  MXV: w('ИМЗ-Урал', KZ, 'Ural'),
  XBB: w('Litex Motors (Great Wall)', BG, 'Great Wall'),

  // Китай
  L6T: w('Geely', CN, 'Geely'),
  LB3: w('Geely', CN, 'Geely'),
  LGW: w('Great Wall Motor (Haval)', CN),
  LVV: w('Chery', CN, 'Chery'),
  LVM: w('Chery Commercial Vehicle', CN, 'Chery'),
  LS5: w('Changan Automobile / Changan Suzuki', CN),
  LVR: w('Changan Mazda', CN, 'Mazda'),
  LVS: w('Changan Ford / Changan Ford Mazda', CN),
  LJ1: w('JAC', CN, 'JAC'),
  LSJ: w('SAIC MG / SAIC Roewe', CN),
  LSV: w('SAIC Volkswagen', CN),
  LSG: w('SAIC-GM (Chevrolet)', CN, 'Chevrolet'),
  LRB: w('SAIC-GM (Buick)', CN, 'Buick'),
  LRE: w('SAIC-GM (Cadillac)', CN, 'Cadillac'),
  LZW: w('SAIC-GM-Wuling', CN),
  LSH: w('SAIC Maxus', CN, 'Maxus'),
  LSK: w('SAIC Maxus', CN, 'Maxus'),
  LFV: w('FAW-Volkswagen', CN),
  LFM: w('FAW Toyota', CN, 'Toyota'),
  LTV: w('FAW Toyota (Тяньцзинь)', CN, 'Toyota'),
  LFP: w('FAW Car', CN),
  LFB: w('FAW Jilin', CN, 'FAW'),
  LH1: w('FAW Haima', CN, 'Haima'),
  LGX: w('BYD Auto', CN, 'BYD'),
  LC0: w('BYD Auto', CN, 'BYD'),
  LA9: w('BYD Auto', CN, 'BYD'),
  LPE: w('BYD Auto', CN, 'BYD'),
  LDC: w('Dongfeng Peugeot-Citroen', CN),
  LGB: w('Dongfeng Nissan', CN, 'Nissan'),
  LGJ: w('Dongfeng Fengshen (Aeolus)', CN, 'Dongfeng'),
  LGG: w('Dongfeng Liuzhou Motor', CN, 'Dongfeng'),
  LGA: w('Dongfeng Commercial Vehicle (грузовики)', CN, 'Dongfeng'),
  LVZ: w('DFSK', CN, 'DFSK'),
  LVH: w('Dongfeng Honda', CN, 'Honda'),
  LJD: w('Dongfeng Yueda Kia', CN, 'Kia'),
  LNB: w('BAIC Motor', CN, 'BAIC'),
  LBE: w('Beijing Hyundai', CN, 'Hyundai'),
  LE4: w('Beijing Benz', CN, 'Mercedes-Benz'),
  LB1: w('Fujian Benz', CN, 'Mercedes-Benz'),
  LBV: w('BMW Brilliance', CN, 'BMW'),
  LSY: w('Brilliance / Jinbei GM', CN),
  LHG: w('Guangzhou Honda', CN, 'Honda'),
  LUC: w('Honda Automobile (China)', CN, 'Honda'),
  LVG: w('GAC Toyota', CN, 'Toyota'),
  LMG: w('GAC Trumpchi', CN, 'GAC'),
  LL6: w('GAC Mitsubishi', CN, 'Mitsubishi'),
  LWV: w('GAC Fiat Chrysler', CN),
  LYV: w('Volvo Cars (Чэнду, Луцяо)', CN, 'Volvo'),
  LVY: w('Volvo Cars (Дацин)', CN, 'Volvo'),
  LPS: w('Polestar', CN, 'Polestar'),
  LRW: w('Tesla (Шанхай)', CN, 'Tesla'),
  LLV: w('Lifan', CN, 'Lifan'),
  LJ8: w('Zotye Auto', CN, 'Zotye'),
  LDN: w('Soueast', CN, 'Soueast'),
  LKC: w('Changhe', CN, 'Changhe'),
  LVF: w('Changhe Suzuki', CN, 'Suzuki'),
  LEF: w('JMC', CN, 'JMC'),
  LJX: w('JMC Ford', CN, 'Ford'),
  LET: w('Jiangxi Isuzu', CN, 'Isuzu'),
  LWL: w('Qingling Isuzu', CN, 'Isuzu'),
  LJN: w('Zhengzhou Nissan', CN, 'Nissan'),
  LVX: w('Landwind', CN, 'Landwind'),
  LPA: w('Changan PSA (DS Automobiles)', CN, 'DS'),
  LLN: w('Qoros', CN, 'Qoros'),
  LM6: w('SWM', CN, 'SWM'),
  LTA: w('ZX Auto', CN, 'ZX Auto'),
  LXV: w('Beijing Borgward Automotive', CN, 'Borgward'),
  L2C: w('Chery Jaguar Land Rover', CN),
  LZZ: w('Sinotruk (Howo, Sitrak)', CN),
  LZG: w('Shaanxi Automobile Group (Shacman)', CN, 'Shacman'),
  LVA: w('Foton Motor', CN, 'Foton'),
  LVB: w('Foton Motor', CN, 'Foton'),
  LVC: w('Foton Motor', CN, 'Foton'),
  LZY: w('Yutong', CN, 'Yutong'),
  LKL: w('Higer Bus', CN, 'Higer'),
  LA6: w('King Long', CN, 'King Long'),
  LL3: w('Xiamen Golden Dragon Bus', CN, 'Golden Dragon'),
  LCE: w('CFMoto', CN, 'CFMoto'),

  // Южная Корея
  KMH: w('Hyundai', KR, 'Hyundai'),
  KM8: w('Hyundai (SUV)', KR, 'Hyundai'),
  KMF: w('Hyundai (фургоны и грузовики)', KR, 'Hyundai'),
  KME: w('Hyundai (грузовики)', KR, 'Hyundai'),
  KMJ: w('Hyundai (автобусы)', KR, 'Hyundai'),
  KMT: w('Genesis', KR, 'Genesis'),
  KMU: w('Genesis (SUV)', KR, 'Genesis'),
  KNA: w('Kia', KR, 'Kia'),
  KNC: w('Kia', KR, 'Kia'),
  KNE: w('Kia', KR, 'Kia'),
  KND: w('Kia (SUV, минивэны)', KR, 'Kia'),
  KNM: w('Renault Samsung Motors', KR),
  KL1: w('GM Korea (Chevrolet)', KR, 'Chevrolet'),
  KL7: w('GM Korea (Chevrolet SUV)', KR, 'Chevrolet'),
  KL8: w('GM Korea (Chevrolet)', KR, 'Chevrolet'),
  KL4: w('GM Korea (Buick)', KR, 'Buick'),
  KLA: w('Daewoo / GM Korea', KR),
  KPT: w('KG Mobility (SsangYong), SUV', KR, 'SsangYong'),
  KPA: w('KG Mobility (SsangYong), пикапы', KR, 'SsangYong'),
  KPB: w('KG Mobility (SsangYong)', KR, 'SsangYong'),

  // Япония
  JA3: w('Mitsubishi', JP, 'Mitsubishi'),
  JA4: w('Mitsubishi (SUV, минивэны)', JP, 'Mitsubishi'),
  JA7: w('Mitsubishi (грузовики)', JP, 'Mitsubishi'),
  JMA: w('Mitsubishi', JP, 'Mitsubishi'),
  JMB: w('Mitsubishi', JP, 'Mitsubishi'),
  JMF: w('Mitsubishi', JP, 'Mitsubishi'),
  JMY: w('Mitsubishi', JP, 'Mitsubishi'),
  JE4: w('Mitsubishi', JP, 'Mitsubishi'),
  JLF: w('Mitsubishi Fuso Truck & Bus', JP, 'Mitsubishi Fuso'),
  JF1: w('Subaru', JP, 'Subaru'),
  JF2: w('Subaru (SUV)', JP, 'Subaru'),
  JHM: w('Honda', JP, 'Honda'),
  JHL: w('Honda (SUV, минивэны)', JP, 'Honda'),
  JH2: w('Honda (мотоциклы)', JP, 'Honda'),
  JH4: w('Acura', JP, 'Acura'),
  JHA: w('Hino', JP, 'Hino'),
  JHB: w('Hino', JP, 'Hino'),
  JHD: w('Hino', JP, 'Hino'),
  JHF: w('Hino', JP, 'Hino'),
  JHH: w('Hino', JP, 'Hino'),
  JM1: w('Mazda', JP, 'Mazda'),
  JM2: w('Mazda (грузовики)', JP, 'Mazda'),
  JM3: w('Mazda (SUV)', JP, 'Mazda'),
  JM6: w('Mazda', JP, 'Mazda'),
  JM7: w('Mazda', JP, 'Mazda'),
  JMZ: w('Mazda (для Европы)', JP, 'Mazda'),
  JM0: w('Mazda (для Океании)', JP, 'Mazda'),
  JN1: w('Nissan (Nissan, Infiniti)', JP),
  JN8: w('Nissan (SUV Nissan, Infiniti)', JP),
  JN6: w('Nissan (грузовики)', JP, 'Nissan'),
  JNK: w('Infiniti', JP, 'Infiniti'),
  JNR: w('Infiniti (SUV)', JP, 'Infiniti'),
  JS2: w('Suzuki', JP, 'Suzuki'),
  JS3: w('Suzuki (SUV)', JP, 'Suzuki'),
  JT2: w('Toyota', JP, 'Toyota'),
  JT3: w('Toyota (SUV, минивэны)', JP, 'Toyota'),
  JT4: w('Toyota (грузовики)', JP, 'Toyota'),
  JTD: w('Toyota', JP, 'Toyota'),
  JTE: w('Toyota (SUV, минивэны)', JP, 'Toyota'),
  JTF: w('Toyota (фургоны, грузовики)', JP, 'Toyota'),
  JTG: w('Toyota (минивэны, автобусы)', JP, 'Toyota'),
  JTK: w('Toyota', JP, 'Toyota'),
  JTL: w('Toyota (SUV)', JP, 'Toyota'),
  JTM: w('Toyota (SUV)', JP, 'Toyota'),
  JTN: w('Toyota', JP, 'Toyota'),
  JTH: w('Lexus', JP, 'Lexus'),
  JT8: w('Lexus', JP, 'Lexus'),
  JTJ: w('Lexus (SUV)', JP, 'Lexus'),
  JT6: w('Lexus (SUV)', JP, 'Lexus'),
  JDA: w('Daihatsu', JP, 'Daihatsu'),
  JD1: w('Daihatsu', JP, 'Daihatsu'),
  JD2: w('Daihatsu (SUV)', JP, 'Daihatsu'),
  JAA: w('Isuzu (грузовики)', JP, 'Isuzu'),
  JAB: w('Isuzu', JP, 'Isuzu'),
  JAC: w('Isuzu (SUV)', JP, 'Isuzu'),
  JYA: w('Yamaha Motor (мотоциклы)', JP, 'Yamaha'),
  JKA: w('Kawasaki', JP, 'Kawasaki'),
  JKB: w('Kawasaki', JP, 'Kawasaki'),

  // Германия
  WAU: w('Audi', DE, 'Audi'),
  WUA: w('Audi Sport / quattro GmbH', DE, 'Audi'),
  WU1: w('Audi Sport (SUV)', DE, 'Audi'),
  WBA: w('BMW', DE, 'BMW'),
  WBS: w('BMW M', DE, 'BMW'),
  WBX: w('BMW (SUV)', DE, 'BMW'),
  WBY: w('BMW i', DE, 'BMW'),
  WB5: w('BMW i (SUV)', DE, 'BMW'),
  WB6: w('BMW M (SUV)', DE, 'BMW'),
  WB1: w('BMW Motorrad', DE, 'BMW'),
  WDB: w('Mercedes-Benz', DE, 'Mercedes-Benz'),
  WDC: w('Mercedes-Benz (SUV)', DE, 'Mercedes-Benz'),
  WDD: w('Mercedes-Benz', DE, 'Mercedes-Benz'),
  WDF: w('Mercedes-Benz (фургоны)', DE, 'Mercedes-Benz'),
  W1K: w('Mercedes-Benz', DE, 'Mercedes-Benz'),
  W1N: w('Mercedes-Benz (SUV)', DE, 'Mercedes-Benz'),
  W1T: w('Mercedes-Benz (грузовики)', DE, 'Mercedes-Benz'),
  W1V: w('Mercedes-Benz (фургоны)', DE, 'Mercedes-Benz'),
  WMX: w('Mercedes-AMG', DE, 'Mercedes-Benz'),
  WEB: w('EvoBus (автобусы Mercedes-Benz)', DE, 'Mercedes-Benz'),
  WME: w('smart', DE, 'smart'),
  W1A: w('smart', DE, 'smart'),
  WMW: w('MINI', DE, 'MINI'),
  WMZ: w('MINI (SUV)', DE, 'MINI'),
  WP0: w('Porsche', DE, 'Porsche'),
  WP1: w('Porsche (SUV)', DE, 'Porsche'),
  WVW: w('Volkswagen', DE, 'Volkswagen'),
  WVG: w('Volkswagen (SUV)', DE, 'Volkswagen'),
  WV1: w('Volkswagen Коммерческие автомобили', DE, 'Volkswagen'),
  WV2: w('Volkswagen Коммерческие автомобили', DE, 'Volkswagen'),
  WF0: w('Ford of Europe', DE, 'Ford'),
  W0L: w('Opel', DE, 'Opel'),
  W0V: w('Opel Automobile', DE, 'Opel'),
  WMA: w('MAN', DE, 'MAN'),
  WJM: w('Iveco Magirus', DE, 'Iveco'),
  WKK: w('Setra (Karl Kässbohrer)', DE, 'Setra'),
  WAG: w('Neoplan', DE, 'Neoplan'),
  WAP: w('Alpina', DE, 'Alpina'),

  // Франция
  VF1: w('Renault', FR, 'Renault'),
  VF3: w('Peugeot', FR, 'Peugeot'),
  VF7: w('Citroen', FR, 'Citroen'),
  VR3: w('Peugeot', FR, 'Peugeot'),
  VR7: w('Citroen', FR, 'Citroen'),
  VR1: w('DS Automobiles', FR, 'DS'),
  VF2: w('Renault Trucks', FR, 'Renault Trucks'),
  VF6: w('Renault Trucks', FR, 'Renault Trucks'),
  VN1: w('Renault SOVAB', FR, 'Renault'),
  VFA: w('Alpine', FR, 'Alpine'),
  VNK: w('Toyota Motor Manufacturing France', FR, 'Toyota'),
  VNV: w('Nissan (Франция)', FR, 'Nissan'),
  VXK: w('Opel / Vauxhall (Франция)', FR, 'Opel'),
  VXE: w('Opel / Vauxhall, фургоны (Франция)', FR, 'Opel'),
  VNE: w('Iveco Bus', FR, 'Iveco'),

  // Испания
  VSS: w('SEAT', ES, 'SEAT'),
  VS5: w('Renault España', ES, 'Renault'),
  VS6: w('Ford España', ES, 'Ford'),
  VS7: w('Citroen (Испания)', ES, 'Citroen'),
  VS8: w('Peugeot (Испания)', ES, 'Peugeot'),
  VSK: w('Nissan Motor Ibérica', ES, 'Nissan'),
  VSX: w('Opel España', ES, 'Opel'),
  VSC: w('Mercedes-Benz España (Витория)', ES, 'Mercedes-Benz'),

  // Италия
  ZFA: w('Fiat', IT, 'Fiat'),
  ZFB: w('Fiat (SUV, минивэны)', IT, 'Fiat'),
  ZFF: w('Ferrari', IT, 'Ferrari'),
  ZAR: w('Alfa Romeo', IT, 'Alfa Romeo'),
  ZAS: w('Alfa Romeo', IT, 'Alfa Romeo'),
  ZAM: w('Maserati', IT, 'Maserati'),
  ZN6: w('Maserati (SUV)', IT, 'Maserati'),
  ZHW: w('Lamborghini', IT, 'Lamborghini'),
  ZPB: w('Lamborghini (SUV)', IT, 'Lamborghini'),
  ZLA: w('Lancia', IT, 'Lancia'),
  ZAC: w('Jeep / Dodge (Италия)', IT),
  ZCF: w('Iveco', IT, 'Iveco'),
  ZDM: w('Ducati', IT, 'Ducati'),
  ZD4: w('Aprilia', IT, 'Aprilia'),
  ZGU: w('Moto Guzzi', IT, 'Moto Guzzi'),

  // Великобритания
  SAJ: w('Jaguar', GB, 'Jaguar'),
  SAD: w('Jaguar (SUV)', GB, 'Jaguar'),
  SAL: w('Land Rover', GB, 'Land Rover'),
  SCA: w('Rolls-Royce', GB, 'Rolls-Royce'),
  SLA: w('Rolls-Royce (SUV)', GB, 'Rolls-Royce'),
  SCB: w('Bentley', GB, 'Bentley'),
  SJA: w('Bentley (SUV)', GB, 'Bentley'),
  SCC: w('Lotus', GB, 'Lotus'),
  SCF: w('Aston Martin', GB, 'Aston Martin'),
  SD7: w('Aston Martin (SUV)', GB, 'Aston Martin'),
  SBM: w('McLaren', GB, 'McLaren'),
  SHH: w('Honda UK', GB, 'Honda'),
  SHS: w('Honda UK (SUV)', GB, 'Honda'),
  SJN: w('Nissan Motor Manufacturing UK', GB, 'Nissan'),
  SJK: w('Nissan Motor Manufacturing UK (Infiniti)', GB, 'Infiniti'),
  SB1: w('Toyota Manufacturing UK', GB, 'Toyota'),
  SAR: w('Rover / MG Rover', GB),
  SDP: w('MG Motor UK', GB, 'MG'),
  SKA: w('Vauxhall', GB, 'Vauxhall'),
  SFA: w('Ford of Britain', GB, 'Ford'),
  SC6: w('INEOS Automotive', GB, 'INEOS'),
  SEY: w('LDV', GB, 'LDV'),

  // Остальная Европа
  TMB: w('Skoda Auto', CZ, 'Skoda'),
  TMA: w('Hyundai Motor Manufacturing Czech', CZ, 'Hyundai'),
  TMC: w('Hyundai Motor Manufacturing Czech (SUV)', CZ, 'Hyundai'),
  TMT: w('Tatra', CZ, 'Tatra'),
  TNT: w('Tatra (грузовики)', CZ, 'Tatra'),
  TNU: w('Tatra (грузовики)', CZ, 'Tatra'),
  TRU: w('Audi (Венгрия)', HU, 'Audi'),
  TSM: w('Suzuki (Венгрия)', HU, 'Suzuki'),
  U5Y: w('Kia Slovakia', SK, 'Kia'),
  U6Y: w('Kia Slovakia (SUV)', SK, 'Kia'),
  UU1: w('Dacia', RO, 'Dacia'),
  UU3: w('ARO', RO, 'ARO'),
  UU6: w('Daewoo Romania', RO, 'Daewoo'),
  YV1: w('Volvo Cars', SE, 'Volvo'),
  YV4: w('Volvo Cars (SUV)', SE, 'Volvo'),
  YV2: w('Volvo Trucks', SE, 'Volvo'),
  YV3: w('Volvo Buses', SE, 'Volvo'),
  YS3: w('Saab', SE, 'Saab'),
  YS2: w('Scania (грузовики)', SE, 'Scania'),
  YS4: w('Scania (автобусы)', SE, 'Scania'),
  YSM: w('Polestar', SE, 'Polestar'),
  YK1: w('Saab (Valmet Automotive)', FI, 'Saab'),
  XLR: w('DAF Trucks', NL, 'DAF'),
  XLB: w('Volvo Car B.V. / NedCar', NL, 'Volvo'),
  XMC: w('NedCar (Mitsubishi)', NL, 'Mitsubishi'),
  XP7: w('Tesla (Гигафабрика Берлин)', DE, 'Tesla'),
  YC1: w('Honda (Бельгия)', BE, 'Honda'),
  YAR: w('Toyota Motor Europe', BE, 'Toyota'),
  TW1: w('Toyota Caetano Portugal', PT, 'Toyota'),
  VX1: w('Zastava', RS, 'Zastava'),

  // Турция
  NMT: w('Toyota Motor Manufacturing Turkey', TR, 'Toyota'),
  NM0: w('Ford Otosan', TR, 'Ford'),
  NM1: w('Oyak-Renault', TR, 'Renault'),
  NM4: w('Tofaş', TR),
  NLH: w('Hyundai Assan', TR, 'Hyundai'),
  NLA: w('Honda (Турция)', TR, 'Honda'),
  NMB: w('Mercedes-Benz Türk', TR, 'Mercedes-Benz'),
  NL1: w('Togg', TR, 'Togg'),

  // США, Канада, Мексика
  '1FA': w('Ford', US, 'Ford'),
  '1FM': w('Ford (SUV, минивэны)', US, 'Ford'),
  '1FT': w('Ford (пикапы)', US, 'Ford'),
  '2FA': w('Ford (Канада)', CA, 'Ford'),
  '2FM': w('Ford (SUV, Канада)', CA, 'Ford'),
  '2FT': w('Ford (пикапы, Канада)', CA, 'Ford'),
  '3FA': w('Ford (Мексика)', MX, 'Ford'),
  '3FM': w('Ford (SUV, Мексика)', MX, 'Ford'),
  '3FT': w('Ford (пикапы, Мексика)', MX, 'Ford'),
  '1G1': w('Chevrolet', US, 'Chevrolet'),
  '1GC': w('Chevrolet (пикапы)', US, 'Chevrolet'),
  '1GN': w('Chevrolet (SUV)', US, 'Chevrolet'),
  '2G1': w('Chevrolet (Канада)', CA, 'Chevrolet'),
  '2GN': w('Chevrolet (SUV, Канада)', CA, 'Chevrolet'),
  '3G1': w('Chevrolet (Мексика)', MX, 'Chevrolet'),
  '3GC': w('Chevrolet (пикапы, Мексика)', MX, 'Chevrolet'),
  '3GN': w('Chevrolet (SUV, Мексика)', MX, 'Chevrolet'),
  '1G4': w('Buick', US, 'Buick'),
  '5GA': w('Buick (SUV)', US, 'Buick'),
  '1G6': w('Cadillac', US, 'Cadillac'),
  '1GY': w('Cadillac (SUV)', US, 'Cadillac'),
  '3GY': w('Cadillac (SUV, Мексика)', MX, 'Cadillac'),
  '1GK': w('GMC (SUV)', US, 'GMC'),
  '1GT': w('GMC (пикапы)', US, 'GMC'),
  '1C3': w('Chrysler Group (все марки), легковые', US),
  '1C4': w('Chrysler Group (все марки), SUV и минивэны', US),
  '1C6': w('Chrysler Group (все марки), пикапы', US),
  '2C3': w('Chrysler Group (все марки), легковые, Канада', CA),
  '1J4': w('Jeep (SUV)', US, 'Jeep'),
  '1J8': w('Jeep (SUV)', US, 'Jeep'),
  '1B3': w('Dodge', US, 'Dodge'),
  '1D7': w('Dodge (пикапы)', US, 'Dodge'),
  '1HG': w('Honda of America (Огайо)', US, 'Honda'),
  '19X': w('Honda Manufacturing of Indiana', US, 'Honda'),
  '5J6': w('Honda (SUV, Огайо)', US, 'Honda'),
  '5FN': w('Honda Manufacturing of Alabama (SUV, минивэны)', US, 'Honda'),
  '7FA': w('Honda Manufacturing of Indiana (SUV)', US, 'Honda'),
  '19U': w('Acura (Огайо)', US, 'Acura'),
  '5J8': w('Acura (SUV, Огайо)', US, 'Acura'),
  '2HG': w('Honda of Canada', CA, 'Honda'),
  '2HK': w('Honda of Canada (SUV)', CA, 'Honda'),
  '2HN': w('Acura (SUV, Канада)', CA, 'Acura'),
  '4T1': w('Toyota Motor Manufacturing Kentucky', US, 'Toyota'),
  '4T3': w('Toyota Motor Manufacturing Kentucky (SUV)', US, 'Toyota'),
  '5TD': w('Toyota (SUV, TMMI)', US, 'Toyota'),
  '5TF': w('Toyota (пикапы, TMMTX)', US, 'Toyota'),
  '5YF': w('Toyota (TMMMS)', US, 'Toyota'),
  '58A': w('Lexus (TMMK)', US, 'Lexus'),
  '2T1': w('Toyota (Канада)', CA, 'Toyota'),
  '2T3': w('Toyota (SUV, Канада)', CA, 'Toyota'),
  '2T2': w('Lexus (SUV, Канада)', CA, 'Lexus'),
  '3TM': w('Toyota (пикапы, Мексика)', MX, 'Toyota'),
  '1N4': w('Nissan', US, 'Nissan'),
  '1N6': w('Nissan (пикапы)', US, 'Nissan'),
  '5N1': w('Nissan / Infiniti (SUV)', US),
  '3N1': w('Nissan (Мексика)', MX, 'Nissan'),
  '4S3': w('Subaru', US, 'Subaru'),
  '4S4': w('Subaru (SUV)', US, 'Subaru'),
  '5NP': w('Hyundai', US, 'Hyundai'),
  '5NM': w('Hyundai (SUV)', US, 'Hyundai'),
  '5XX': w('Kia', US, 'Kia'),
  '5XY': w('Kia / Hyundai (SUV)', US),
  '3KP': w('Kia / Hyundai (Мексика)', MX),
  '5YJ': w('Tesla', US, 'Tesla'),
  '7SA': w('Tesla (SUV)', US, 'Tesla'),
  '7G2': w('Tesla (Cybertruck, Semi)', US, 'Tesla'),
  '4US': w('BMW', US, 'BMW'),
  '5UX': w('BMW (SUV)', US, 'BMW'),
  '5YM': w('BMW M (SUV)', US, 'BMW'),
  '3MW': w('BMW (Мексика)', MX, 'BMW'),
  '4JG': w('Mercedes-Benz (SUV)', US, 'Mercedes-Benz'),
  '55S': w('Mercedes-Benz', US, 'Mercedes-Benz'),
  '1VW': w('Volkswagen', US, 'Volkswagen'),
  '1V2': w('Volkswagen (SUV)', US, 'Volkswagen'),
  '3VW': w('Volkswagen (Мексика)', MX, 'Volkswagen'),
  '3VV': w('Volkswagen (SUV, Мексика)', MX, 'Volkswagen'),
  '1LN': w('Lincoln', US, 'Lincoln'),
  '5LM': w('Lincoln (SUV)', US, 'Lincoln'),
  '1ME': w('Mercury', US, 'Mercury'),
  '4A3': w('Mitsubishi Motors (США)', US, 'Mitsubishi'),
  '4A4': w('Mitsubishi Motors (SUV, США)', US, 'Mitsubishi'),
  '1YV': w('Mazda (США)', US, 'Mazda'),
  '7MM': w('Mazda (SUV, MTMUS)', US, 'Mazda'),
  '3MZ': w('Mazda (Мексика)', MX, 'Mazda'),
  '3MV': w('Mazda (SUV, Мексика)', MX, 'Mazda'),
  '7JR': w('Volvo Cars (США)', US, 'Volvo'),
  '5GR': w('Hummer H2', US, 'Hummer'),
  '5GT': w('Hummer H3', US, 'Hummer'),
  '7PD': w('Rivian (SUV)', US, 'Rivian'),
  '7FC': w('Rivian (пикапы)', US, 'Rivian'),

  // Южная Америка
  '9BW': w('Volkswagen do Brasil', BR, 'Volkswagen'),
  '9BG': w('General Motors do Brasil (Chevrolet)', BR, 'Chevrolet'),
  '9BD': w('Fiat Automóveis', BR, 'Fiat'),
  '9BF': w('Ford Brasil', BR, 'Ford'),
  '9BR': w('Toyota (Бразилия)', BR, 'Toyota'),
  '9BH': w('Hyundai Motor Brasil', BR, 'Hyundai'),
  '93H': w('Honda (Бразилия)', BR, 'Honda'),
  '935': w('Citroen (Бразилия)', BR, 'Citroen'),
  '936': w('Peugeot (Бразилия)', BR, 'Peugeot'),
  '93Y': w('Renault do Brasil', BR, 'Renault'),
  '94D': w('Nissan (Бразилия)', BR, 'Nissan'),
  '8AP': w('Fiat (Аргентина)', AR, 'Fiat'),
  '8AG': w('General Motors de Argentina (Chevrolet)', AR, 'Chevrolet'),
  '8AJ': w('Toyota Argentina', AR, 'Toyota'),
  '8AW': w('Volkswagen Argentina', AR, 'Volkswagen'),
  '8AF': w('Ford Motor Argentina', AR, 'Ford'),
  '8A1': w('Renault Argentina', AR, 'Renault'),
  '8AD': w('Peugeot (Аргентина)', AR, 'Peugeot'),

  // Азия, Африка, Океания
  MA1: w('Mahindra', IN, 'Mahindra'),
  MA3: w('Maruti Suzuki India', IN, 'Suzuki'),
  MAT: w('Tata Motors', IN, 'Tata'),
  MAL: w('Hyundai Motor India', IN, 'Hyundai'),
  MAJ: w('Ford India', IN, 'Ford'),
  MAK: w('Honda Cars India', IN, 'Honda'),
  MBJ: w('Toyota Kirloskar Motor', IN, 'Toyota'),
  MZB: w('Kia India', IN, 'Kia'),
  MDH: w('Nissan Motor India', IN, 'Nissan'),
  MEE: w('Renault India', IN, 'Renault'),
  MRH: w('Honda (Таиланд)', TH, 'Honda'),
  MR0: w('Toyota (Таиланд)', TH, 'Toyota'),
  MR1: w('Toyota (Таиланд)', TH, 'Toyota'),
  MR2: w('Toyota (Таиланд)', TH, 'Toyota'),
  ML3: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MMA: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MMB: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MMC: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MMD: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MMT: w('Mitsubishi Motors (Таиланд)', TH, 'Mitsubishi'),
  MM0: w('Mazda (AutoAlliance, Таиланд)', TH, 'Mazda'),
  MM6: w('Mazda (AutoAlliance, Таиланд)', TH, 'Mazda'),
  MM7: w('Mazda (AutoAlliance, Таиланд)', TH, 'Mazda'),
  MM8: w('Mazda (AutoAlliance, Таиланд)', TH, 'Mazda'),
  MNT: w('Nissan Motor Thailand', TH, 'Nissan'),
  MPA: w('Isuzu Motors (Таиланд)', TH, 'Isuzu'),
  MP1: w('Isuzu Motors (Таиланд)', TH, 'Isuzu'),
  MNA: w('Ford (AutoAlliance, Таиланд)', TH, 'Ford'),
  MNB: w('Ford (AutoAlliance, Таиланд)', TH, 'Ford'),
  MNC: w('Ford (AutoAlliance, Таиланд)', TH, 'Ford'),
  MPB: w('Ford (FTM, Таиланд)', TH, 'Ford'),
  MMM: w('Chevrolet (Таиланд)', TH, 'Chevrolet'),
  MML: w('MG (Таиланд)', TH, 'MG'),
  MMS: w('Suzuki (Таиланд)', TH, 'Suzuki'),
  MHF: w('Toyota Astra Motor', ID, 'Toyota'),
  MHR: w('Honda Prospect Motor', ID, 'Honda'),
  MK2: w('Mitsubishi Motors Krama Yudha', ID, 'Mitsubishi'),
  PL1: w('Proton', MY, 'Proton'),
  PM2: w('Perodua', MY, 'Perodua'),
  NAA: w('Iran Khodro', IR, 'Iran Khodro'),
  NAS: w('SAIPA', IR, 'SAIPA'),
  RKL: w('Kuozui Motors (Toyota)', TW, 'Toyota'),
  RLL: w('VinFast', VN, 'VinFast'),
  AAV: w('Volkswagen of South Africa', ZA, 'Volkswagen'),
  AHT: w('Toyota South Africa Motors', ZA, 'Toyota'),
  AFA: w('Ford Motor Company of Southern Africa', ZA, 'Ford'),
  ABM: w('BMW Southern Africa', ZA, 'BMW'),
  '6T1': w('Toyota (Австралия)', AU, 'Toyota'),
  '6FP': w('Ford (Австралия)', AU, 'Ford'),
  '6MM': w('Mitsubishi (Австралия)', AU, 'Mitsubishi'),
  '6F4': w('Nissan Motor Australia', AU, 'Nissan'),
}

/** Порядок символов в диапазонах ISO 3780 (буквы I, O, Q в VIN не бывают). */
const SECOND_CHAR_ORDER = 'ABCDEFGHJKLMNPRSTUVWXYZ1234567890'

function expandRegions(ranges: [string, string][]): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [chars, region] of ranges) for (const c of chars) out[c] = region
  return out
}

/**
 * Регион по первому символу (ISO 3779 в редакции, действующей по данным Wikipedia на 2025 год):
 * A–C Африка, H–R Азия, E и S–Z Европа, 1–5 и 7 Северная Америка, 6 Океания, 8–9 Южная Америка.
 * D, F, G и 0 не распределены.
 */
export const REGION_BY_FIRST_CHAR: Record<string, string> = expandRegions([
  ['ABC', 'Африка'],
  ['HJKLMNPR', 'Азия'],
  ['ESTUVWXYZ', 'Европа'],
  ['123457', 'Северная Америка'],
  ['6', 'Океания'],
  ['89', 'Южная Америка'],
])

/**
 * Страна по первым двум символам (ISO 3780). Строка — `первый символ`, `диапазон второго символа`, страна;
 * пустой диапазон — любой второй символ. Более узкие диапазоны идут раньше общих.
 */
const COUNTRY_RANGES: [string, string, string][] = [
  ['A', 'AH', 'ЮАР'], ['A', 'JK', 'Кот-д’Ивуар'], ['A', 'LM', 'Лесото'], ['A', 'NP', 'Ботсвана'],
  ['A', 'RS', 'Намибия'], ['A', 'TU', 'Мадагаскар'], ['A', 'VW', 'Маврикий'], ['A', 'XY', 'Тунис'],
  ['A', 'Z1', 'Кипр'], ['A', '23', 'Зимбабве'], ['A', '45', 'Мозамбик'],
  ['B', 'AB', 'Ангола'], ['B', 'CC', 'Эфиопия'], ['B', 'FG', 'Кения'], ['B', 'HH', 'Руанда'], ['B', 'LL', 'Нигерия'],
  ['B', 'RR', 'Алжир'], ['B', 'TT', 'Эсватини'], ['B', 'UU', 'Уганда'], ['B', '34', 'Ливия'],
  ['C', 'AB', 'Египет'], ['C', 'FG', 'Марокко'], ['C', 'LM', 'Замбия'],
  ['E', '', 'Россия'],
  ['H', '', 'Китай'],
  ['J', '', 'Япония'],
  ['K', 'FH', 'Израиль'], ['K', 'LR', 'Южная Корея'], ['K', 'ST', 'Иордания'], ['K', '13', 'Южная Корея'],
  ['K', '55', 'Киргизия'],
  ['L', '', 'Китай'],
  ['M', 'AE', 'Индия'], ['M', 'FK', 'Индонезия'], ['M', 'LR', 'Таиланд'], ['M', 'SS', 'Мьянма'], ['M', 'UU', 'Монголия'],
  ['M', 'XX', 'Казахстан'], ['M', 'Y0', 'Индия'],
  ['N', 'AE', 'Иран'], ['N', 'FG', 'Пакистан'], ['N', 'JJ', 'Ирак'], ['N', 'LR', 'Турция'], ['N', 'ST', 'Узбекистан'],
  ['N', 'VV', 'Азербайджан'], ['N', 'XX', 'Таджикистан'], ['N', 'YY', 'Армения'], ['N', '15', 'Иран'], ['N', '78', 'Турция'],
  ['P', 'AC', 'Филиппины'], ['P', 'FG', 'Сингапур'], ['P', 'LR', 'Малайзия'], ['P', 'ST', 'Бангладеш'],
  ['P', 'VV', 'Камбоджа'], ['P', '50', 'Индия'],
  ['R', 'AB', 'ОАЭ'], ['R', 'FK', 'Тайвань'], ['R', 'LN', 'Вьетнам'], ['R', 'PP', 'Лаос'], ['R', 'ST', 'Саудовская Аравия'],
  ['R', '17', 'Гонконг'],
  ['S', 'AM', 'Великобритания'], ['S', 'NT', 'Германия'], ['S', 'UZ', 'Польша'], ['S', '12', 'Латвия'], ['S', '33', 'Грузия'],
  ['S', '44', 'Исландия'],
  ['T', 'AH', 'Швейцария'], ['T', 'JP', 'Чехия'], ['T', 'RV', 'Венгрия'], ['T', 'W2', 'Португалия'], ['T', '35', 'Сербия'],
  ['T', '66', 'Андорра'], ['T', '78', 'Нидерланды'],
  ['U', 'AC', 'Испания'], ['U', 'HM', 'Дания'], ['U', 'NR', 'Ирландия'], ['U', 'UX', 'Румыния'],
  ['U', '12', 'Северная Македония'], ['U', '57', 'Словакия'], ['U', '80', 'Босния и Герцеговина'],
  ['V', 'AE', 'Австрия'], ['V', 'FR', 'Франция'], ['V', 'SW', 'Испания'], ['V', 'X2', 'Франция'], ['V', '35', 'Хорватия'],
  ['V', '68', 'Эстония'],
  ['W', '', 'Германия'],
  ['X', 'AC', 'Болгария'], ['X', 'DE', 'Россия'], ['X', 'FH', 'Греция'], ['X', 'JK', 'Россия'], ['X', 'LR', 'Нидерланды'],
  ['X', 'SW', 'Россия'], ['X', 'XY', 'Люксембург'], ['X', 'Z0', 'Россия'],
  ['Y', 'AE', 'Бельгия'], ['Y', 'FK', 'Финляндия'], ['Y', 'NN', 'Мальта'], ['Y', 'SW', 'Швеция'], ['Y', 'X2', 'Норвегия'],
  ['Y', '35', 'Беларусь'], ['Y', '69', 'Украина'],
  ['Z', 'AU', 'Италия'], ['Z', 'XZ', 'Словения'], ['Z', '11', 'Сан-Марино'], ['Z', '35', 'Литва'], ['Z', '60', 'Россия'],
  ['1', '', 'США'], ['2', '', 'Канада'],
  ['3', 'AX', 'Мексика'], ['3', '44', 'Никарагуа'], ['3', '55', 'Доминиканская Республика'], ['3', '66', 'Гондурас'],
  ['3', '77', 'Панама'], ['3', '89', 'Пуэрто-Рико'],
  ['4', '', 'США'], ['5', '', 'США'], ['7', '', 'США'],
  ['6', 'Y1', 'Новая Зеландия'], ['6', '', 'Австралия'],
  ['8', 'AE', 'Аргентина'], ['8', 'FG', 'Чили'], ['8', 'LN', 'Эквадор'], ['8', 'SW', 'Перу'], ['8', 'XZ', 'Венесуэла'],
  ['8', '22', 'Боливия'], ['8', '44', 'Коста-Рика'],
  ['9', 'AE', 'Бразилия'], ['9', 'FG', 'Колумбия'], ['9', 'SV', 'Уругвай'], ['9', '10', 'Бразилия'],
]

/** Страна по первым двум символам VIN; undefined — код не распределён. */
export function countryByCode(first: string, second: string): string | undefined {
  const pos = SECOND_CHAR_ORDER.indexOf(second)
  for (const [f, range, country] of COUNTRY_RANGES) {
    if (f !== first) continue
    if (range === '') return country
    const from = SECOND_CHAR_ORDER.indexOf(range[0]!)
    const to = SECOND_CHAR_ORDER.indexOf(range[1]!)
    if (pos >= from && pos <= to) return country
  }
  return undefined
}
